cflags = -O1 -Wall -pedantic
ipath = /usr/local

all:V: o.asm
clean:V:
	rm -f *.o o.* data.h

install:V: all
	cp o.asm $ipath/bin/65816a

main.o: asm.h data.h
data.h:D: datagen
	./datagen >$target

o.%: %.o
	c99 $prereq -o $target

%.o: %.c data.h
	c99 $cflags -c $stem.c
