(in-package :c)

(proc (main int) (x)
  (var y int 0)
  (if (> x y) (++ x))
  (if (>= x y) (++ x))
  (if (< x y) (++ x))
  (if (<= x y) (++ x))
  (for ((= x (+ (- 1 -1) 0)) (&& 1 (< x (+ 1 9))) (++ y))
    (switch x
      (0 (main x))
      (1 (main (+ x (+ 1 3))))
      (2)
      (3 (main (main (main (main (++ x))))))
      (default (do-while x (+ 1 (-- x))))
      (4 (continue))))
  (return (+ x y)))
